# source: Adapted from "What Happens in the Lunchroom,
# Stays in the Lunchroom", a Woo! Jr production.

adj_0 = input('Enter an adjective: ')
adj_1 = input('Enter an adjective: ')
food_0 = input('Enter a food: ')
food_1 = input('Enter a food: ')
food_2 = input('Enter a food: ')
food_3 = input('Enter a food: ')
food_4 = input('Enter a food: ')
verb_0 = input('Enter a verb: ')
verb_1 = input('Enter a verb: ')
verb_past_tense_0 = input('Enter a verb in the past tense: ')
noun_0 = input('Enter a noun: ')
noun_1 = input('Enter a noun: ')
vegetable_0 = input('Enter a type of vegetable: ')
fruit_0 = input('Enter a type of fruit: ')
furniture_0 = input('Enter a piece of furniture: ')
emotion_0 = input('Enter an emotion: ')


print('Lunchtime in the cafeteria is always')
print(adj_0 + '. They serve hot ' + food_0 + ' and')
print(food_1 + ', but some students ' + verb_0 + ' their')
print('own ' + noun_0 + ' to eat. Some kids quietly')
print(verb_1 + ' their ' + food_2 + ', while others')
print('throw ' + vegetable_0 + ' or ' + fruit_0 + ' when the')
print("teachers aren't looking. One time, a bunch")
print('of kids mixed all of their unfinished ' + food_3)
print('and' + food_4 + ' together to make a ' + adj_1)
print('mountain of ' + noun_1 + ' on a ' + furniture_0 + ' . The')
print('teachers were ' + emotion_0 + ', but everyone')
print('had already ' + verb_past_tense_0 + ' outside for recess,')
print(' so nobody got in trouble.')
